yoda.index:
    path: /
    controller: App\Controller\MainController::indexAction

# Yoda API namespace#

yoda_api.send_message:
    path: /api/send_message
    controller: App\Controller\YodaBotController::sendMessageAction
    methods: [POST]

yoda_api.clear_history:
    path: /api/clear_history
    controller: App\Controller\YodaBotController::clearHistoryAction
    methods: [POST]