parameters:
    inbenta.api_key:                      "%env(string:INBENTA_API_KEY)%"
    inbenta.secret_key:                   "%env(string:INBENTA_SECRET_KEY)%"
    inbenta.authentication_uri:           "%env(string:INBENTA_AUTHENTICATION_URI)%"
    inbenta.api_version:                  "%env(string:INBENTA_API_VERSION)%"
    inbenta.graph_api_url:                "%env(string:INBENTA_GRAPH_API_URL)%"
    inbenta.client.class:                 App\InbentaClient\InbentaClient
    inbenta.graph_api_client.class:       App\InbentaGraphApiClient\InbentaGraphApiClient
    inbenta.authentication_service_class: App\Service\AuthenticationService
    yoda_bot.send_message_client.class:   App\YodaBotClient\YodaBotSendMessageClient
    yoda_bot.yoda_bot_service.class:      App\Service\YodaBotService
    utility.yoda_bot_text_analyzer.class: App\Utility\YodaBotTextAnalyzer

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $inbentaApiKey: "%inbenta.api_key%"
            string $inbentaSecretKey: "%inbenta.secret_key%"
            string $inbentaAuthenticationUri: "%inbenta.authentication_uri%"
            string $inbentaApiVersion: "%inbenta.api_version%"
            string $inbentaGraphApiUrl: "%inbenta.graph_api_url%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    utility.yoda_bot_text_analyzer:
        class: '%utility.yoda_bot_text_analyzer.class%'

    inbenta.client:
        class: '%inbenta.client.class%'
        arguments:
            - '@http_client'
            - '@session'
            - '@inbenta.authentication_service'
            - '@logger'

    inbenta.graph_api_client:
        class: '%inbenta.graph_api_client.class%'
        arguments:
            - '@http_client'

    inbenta.authentication_service:
        class: '%inbenta.authentication_service_class%'
        arguments:
            - '@http_client'
            - '@session'

    yoda_bot.yoda_bot_service:
        class: '%yoda_bot.yoda_bot_service.class%'
        arguments:
            - '@yoda_bot.send_message_client'
            - '@session'

    yoda_bot.send_message_client:
        class: '%yoda_bot.send_message_client.class%'
        arguments:
            - '@inbenta.client'
            - '@inbenta.graph_api_client'
            - '@session'
            - '@utility.yoda_bot_text_analyzer'